version: '3'
services:
  web:
    build: .
    image: iomega/ms2ldaviz
    depends_on:
     - db
     - redis
     - cache
    volumes:
     - jobs:/code/ms2ldaviz/media
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: j7z3rL40w9
      POSTGRES_USER: django
    volumes:
     - datadir:/var/lib/postgresql/data
  worker:
    build: .
    image: iomega/ms2ldaviz
    command: [celery, -A, ms2ldaviz, worker, -l, info, --max-tasks-per-child, '20', --concurrency, '1']
    depends_on:
     - db
     - redis
    volumes:
     - jobs:/code/ms2ldaviz/media
  proxy:
    image: nginx:alpine
    volumes:
      - ./ms2ldaviz/static:/static:ro
      - ./docker.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${PORT:-8001}:80"
    depends_on:
      - web
volumes:
  jobs:
  datadir:
